# -*- coding: utf-8 -*-
"""Conditional_Execution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1neeLusSMcko6qyJ4F6G1bC238C14gjmd
"""

#Simple Interest(Choosing Mnemonic variable names-principal,time_period,rate)

principal=float(input("enter the principal value"))
time_period=float(input("enter the timeperiod"))
rate=float(input("enter the rate"))
interest=(principal*time_period*rate)/100
print(interest)

s1="hello good morning"
len(s1)

print(s1)

s2="hello"
print(s2[1])

s1[-1]

s1[-2]

s1[:]

s1="how are you"
s1[::]

s1[5:10]

s1[:10:2]

#Boolean Expressions(Relational Operators-Comparison Operators <,<=,>,>=,==,!=)
print(2==2)
print(2.5>=3.9)
print(1!=5)

a=15
b=100
c=a>b
d=a<b
print(c,d,sep="   ***   ")

#Logical Operators-and,or,not
1<2<3

1<2 and 2<3

1==1 or 3<2

not(2>3)

not(2<3)

a=2
b=3
c=4
d=5
print(b>a and c>a)
print(c>d or d>c)
print(not(c>d))

#Conditional Execution:if ,if else,elif,nested if
a=int(input("Enter the value of a"))
b=int(input("Enter the value of b"))
if (a>b):
  print("a is greater than b")
print("outside of if block")

a=int(input("Enter the value of a"))#Alternate Execution
b=int(input("Enter the value of b"))
if (a>b):
  print("a is greater than b")
else:
  print(a," is not greater than",b)
print("out of if else block")

a=5
b=15
if (a<b):print("a is less than b")

#Nested if(largest of three numbers)
x=int(input("enter x value"))
y=int(input("enter y value"))
z=int(input("enter z value"))
if x>y:
  if x>z:
    print(x,"is largest")
  else:
    print(z,"is largest") 
else:
  if y>z:
    print(y,"is greatest")
  else:
    print(z,"is largest")

x,y,z=10,30,20#chained conditions
if x>y and x>z:
  print(x,"is greatest")
elif y>x and y>z:
  print(y,"is largest")
else:
  print(z,"is largest")

